#!/bin/bash
set -e

## install dep and devDep
if [ ! -d node_modules ]; then
  ./install-lib-dep
fi
if [ ! -d node_modules/typescript ]; then
  npm i typescript
fi

## build
./gen-index
npm run build:lib

## clean up devDep
rm -rf node_modules
./install-lib-dep

echo "done."
