#!/bin/bash
## generate component
tmp="gc.$RANDOM.tmp"
for a in $@; do
  ./ionic g component "$a"
  ./ng g component "$a" | tee "$tmp"
  m=$(cat "$tmp" | head -n 1 | awk '{print $2}' | awk -F '/' '{print $NF}' | sed 's/.component.scss$//')
  classname=$(cat "src/app/$m/$m.component.ts" | grep class | awk '{print $3}')
  mv "src/app/$m/$m.component.spec.ts" "src/components/$m/$m.component.spec.ts"
  rm "src/app/$m" -rf
  mv "src/components/$m/$m.ts" "src/components/$m/$m.component.ts"
  mv "src/components/$m/$m.html" "src/components/$m/$m.component.html"
  sed -i "s/$m.html/$m.component.html/" "src/components/$m/$m.component.ts"
  sed -i "/$classname/,+1 d" src/app/app.module.ts
  sed -i "s,'./$m/$m',\"./$m/$m.component\"," src/components/components.module.ts
done
rm "$tmp"
