#!/bin/bash
./auto-init
name="kmg"
run_ionic="npm run ionic:serve"
run_horizon="hz serve --dev --bind 0.0.0.0 --token-secret 65a301e1484863cb50359f118e1972c0"
run_game="./dev"
hash "tmux" 2>/dev/null
if [ $? == 0 ]; then
  ## has tmux installed
  tmux start
  tmux new -dP -s ionic "$run_ionic"
  cd "../$name-horizon"
  tmux new -dP -s hz "$run_horizon"
  cd "../kmg-game"
  tmux new -dP -s kmg-game "$run_game"
  cd "../$name-ionic"
  tmux attach -t ionic
else
  ## do not has tmux installed
  cd "../$name-horizon"
  $run_horizon &
  cd "../kmg-game"
  $run_game &
  cd "../$name-ionic"
  $run_ionic
fi
