#!/bin/bash
./auto-init
name="kmg"
run_ionic="npm run ionic:serve"
run_phaser="./dev"
hash "tmux" 2>/dev/null
if [ $? == 0 ]; then
  ## has tmux installed
  tmux start
  tmux new -dP -s ionic "$run_ionic"
  cd "../kmg-phaser"
  tmux new -dP -s kmg-phaser "$run_phaser"
  cd "../$name-ionic"
  tmux attach -t ionic
else
  ## do not has tmux installed
  cd "../kmg-phaser"
  $run_phaser &
  cd "../$name-ionic"
  $run_ionic
fi
